### ISSUE TITLE
Lazer exporting no longer launching on Arch Linux with bin32-jre

### ISSUE THREAD

**Issue by ungeskriptet** [ringosham/Lazer-exporter#14] opened 2021-10-02 08:55 UTC
Lazer exporter was working fine when it suddenly no longer wants to launch.

**Error**
```
╭─david@david-ryuzu ~/Downloads 
╰─$ java32 -jar Lazer_exporter.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:873)
Caused by: java.lang.UnsupportedOperationException: Internal Error
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:158)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:140)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:147)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:279)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	... 5 more
```
It seems like it's missing JavaFX or something?

**To Reproduce**

- Be on Arch Linux
- `paru -Syu bin32-jre` # for 32-bit Java 8
- java32 -jar Lazer_exporter.jar

**Expected behavior**
Lazer exporter launches without problems

**Desktop**
- OS: Arch Linux on GNOME X11

**Additional context**
Maybe the [bin32-jre](https://aur.archlinux.org/packages/bin32-jre) maintainers changed something?

**Comment by ringosham** [comment] 2021-10-02 10:28
This seems like something from upstream.

Try running the jar in 64 bit Java.
It's fine since 32 bit is only used on ffmpeg, not the jar itself.

**Comment by ungeskriptet** [comment] 2021-10-03 10:54
```
╭─david@david-ryuzu ~/.local/bin 
╰─$ java -jar lazer-exporter.jar  
Error: Could not find or load main class com.ringosham.Main
╭─david@david-ryuzu ~/.local/bin 
╰─$ java -version                                                           1 ↵
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

Still no luck

**Comment by ringosham** [comment] 2021-10-03 12:49
This looks like a duplicate of #11. I'm going to close it here

**Closed as completed** 2021-10-03 12:49 UTC
Labels: bug
