### ISSUE TITLE
Cannot run the jar file on macOS

### ISSUE THREAD

**Issue by TuxPenguin09** [ringosham/Lazer-exporter#12] opened 2021-08-26 02:46 UTC
**Describe the bug**
Can't open the jar file from Finder so I opened it via Terminal and yep, it has an error

**To Reproduce**
1. Open JAR via Terminal `java -jar Lazer_exporter`

**Expected behavior**
It just pops up
`Error: Could not find or load main class com.ringosham.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application`

**Desktop (please complete the following information):**
 - OS: macOS Monterey Beta 6

**Additional context**
None

**Comment by ringosham** [comment] 2021-08-26 18:43
What is your Java version? It won't run on anything newer than 8

**Comment by ringosham** [comment] 2021-08-28 12:41
Close as duplicate of #11

**Closed as completed by ringosham** 2021-08-28 12:41 UTC
Labels: bug
